# Generated by Django 2.0.3 on 2018-04-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.IntegerField(choices=[(1, 'Text')])),
                ('text', models.CharField(max_length=255)),
                ('reply_text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reply.Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Postback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.IntegerField(choices=[(1, 'Text')])),
                ('data', models.TextField(max_length=300)),
                ('reply_text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reply.Text')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
