# Generated by Django 2.0.3 on 2018-04-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Keyword text'),
        ),
        migrations.AlterField(
            model_name='postback',
            name='data',
            field=models.TextField(max_length=300, verbose_name='Postback data'),
        ),
    ]
