# Generated by Django 2.0.3 on 2018-04-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
        ('action', '0002_alter_field_text_and_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.IntegerField(choices=[(1, 'Text')])),
                ('reply_text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reply.Text')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
