# Generated by Django 2.0.3 on 2018-04-22 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_invalidmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidmessage',
            name='reply_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reply.Text'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reply.Text'),
        ),
        migrations.AlterField(
            model_name='postback',
            name='reply_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reply.Text'),
        ),
    ]
