# Generated by Django 2.0.3 on 2018-04-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_group_groupitem'),
        ('action', '0004_allow_null_on_field_reply_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidmessage',
            name='reply_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reply.Group'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reply.Group'),
        ),
        migrations.AddField(
            model_name='postback',
            name='reply_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reply.Group'),
        ),
        migrations.AlterField(
            model_name='invalidmessage',
            name='reply',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Group')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Group')]),
        ),
        migrations.AlterField(
            model_name='postback',
            name='reply',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Group')]),
        ),
    ]
