# Generated by Django 2.0.3 on 2018-04-22 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0004_auto_20180422_1113'),
        ('action', '0005_auto_20180422_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidmessage',
            name='reply_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reply.Image'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reply.Image'),
        ),
        migrations.AddField(
            model_name='postback',
            name='reply_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reply.Image'),
        ),
        migrations.AlterField(
            model_name='invalidmessage',
            name='reply',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Group'), (3, 'Image')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Group'), (3, 'Image')]),
        ),
        migrations.AlterField(
            model_name='postback',
            name='reply',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Group'), (3, 'Image')]),
        ),
    ]
