# Generated by Django 2.0.6 on 2018-07-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linecms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='items',
            field=models.ManyToManyField(
                blank=True,
                related_name='_message_items_+',
                to='linecms.Message',
                verbose_name='Group Items'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(
                blank=True, max_length=2000, null=True, verbose_name='Text'),
        ),
    ]
