# Generated by Django 2.0.6 on 2018-07-15 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linecms', '0002_make_message_fields_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessageHook',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('task_type',
                 models.IntegerField(
                     choices=[(1, 'Send Message')], verbose_name='Task type')),
                ('keyword',
                 models.TextField(max_length=2000, verbose_name='Keyword')),
                ('case_sensitive',
                 models.BooleanField(
                     default=False, verbose_name='Case sensitive')),
                ('message',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='linecms.Message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
