# Generated by Django 2.0.3 on 2018-04-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('text', models.TextField(
                    max_length=2000, verbose_name='Text')),
            ],
        ),
    ]
