# Generated by Django 2.0.3 on 2018-04-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.IntegerField(choices=[(1, 'Text'), (2, 'Group')])),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_item_set', to='reply.Group')),
                ('reply_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reply.Group')),
                ('reply_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reply.Text')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
