# Generated by Django 2.0.3 on 2018-04-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_group_groupitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupitem',
            name='reply_group',
        ),
    ]
