# Generated by Django 2.0.3 on 2018-04-22 11:04

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0003_remove_groupitem_reply_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='groupitem',
            name='reply',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Group'), (3, 'Image')]),
        ),
        migrations.AddField(
            model_name='groupitem',
            name='reply_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reply.Image'),
        ),
    ]
